#!/usr/bin/env bash

mkdir -p ../president/
curl -o ../president/alabama-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/alabama/president.json
curl -o ../president/alaska-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/alaska/president.json
curl -o ../president/arizona-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/arizona/president.json
curl -o ../president/arkansas-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/arkansas/president.json
curl -o ../president/california-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/california/president.json
curl -o ../president/colorado-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/colorado/president.json
curl -o ../president/connecticut-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/connecticut/president.json
curl -o ../president/delaware-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/delaware/president.json
curl -o ../president/florida-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/florida/president.json
curl -o ../president/georgia-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/georgia/president.json
curl -o ../president/hawaii-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/hawaii/president.json
curl -o ../president/idaho-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/idaho/president.json
curl -o ../president/illinois-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/illinois/president.json
curl -o ../president/indiana-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/indiana/president.json
curl -o ../president/iowa-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/iowa/president.json
curl -o ../president/kansas-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/kansas/president.json
curl -o ../president/kentucky-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/kentucky/president.json
curl -o ../president/louisiana-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/louisiana/president.json
curl -o ../president/maine-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/maine/president.json
curl -o ../president/maryland-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/maryland/president.json
curl -o ../president/massachusetts-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/massachusetts/president.json
curl -o ../president/michigan-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/michigan/president.json
curl -o ../president/minnesota-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/minnesota/president.json
curl -o ../president/mississippi-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/mississippi/president.json
curl -o ../president/missouri-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/missouri/president.json
curl -o ../president/montana-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/montana/president.json
curl -o ../president/nebraska-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/nebraska/president.json
curl -o ../president/nevada-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/nevada/president.json
curl -o ../president/new-hampshire-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/new-hampshire/president.json
curl -o ../president/new-jersey-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/new-jersey/president.json
curl -o ../president/new-mexico-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/new-mexico/president.json
curl -o ../president/new-york-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/new-york/president.json
curl -o ../president/north-carolina-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/north-carolina/president.json
curl -o ../president/north-dakota-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/north-dakota/president.json
curl -o ../president/ohio-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/ohio/president.json
curl -o ../president/oklahoma-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/oklahoma/president.json
curl -o ../president/oregon-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/oregon/president.json
curl -o ../president/pennsylvania-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/pennsylvania/president.json
curl -o ../president/rhode-island-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/rhode-island/president.json
curl -o ../president/south-carolina-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/south-carolina/president.json
curl -o ../president/south-dakota-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/south-dakota/president.json
curl -o ../president/tennessee-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/tennessee/president.json
curl -o ../president/texas-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/texas/president.json
curl -o ../president/utah-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/utah/president.json
curl -o ../president/vermont-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/vermont/president.json
curl -o ../president/virginia-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/virginia/president.json
curl -o ../president/washington-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/washington/president.json
curl -o ../president/west-virginia-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/west-virginia/president.json
curl -o ../president/wisconsin-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/wisconsin/president.json
curl -o ../president/wyoming-president.json https://static01.nyt.com/elections-assets/2020/data/api/2020-11-03/race-page/wyoming/president.json
